name: "godot-ci export"
on: push
  #pull_request:
  #  branches: ["develop"]
  #  types: closed
env:
  #GODOT_VERSION: "4.3"
  EXPORT_NAME: test-project
  PROJECT_PATH: test-project
jobs:
  version:
    name: Extract project Godot version
    runs-on: ubuntu-24.04
    outputs:
      godot_version: ${{ steps.extract_version.outputs.godot_version }}
      build_name: ${{ steps.name.outputs.build_name }}
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        
      - name: Compute short SHA
        run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build name
        id: name
        run: |
          BUILD_NAME="${{ env.EXPORT_NAME }}-web-${SHA_SHORT}"
          echo "build_name=$BUILD_NAME" >> $GITHUB_OUTPUT
        
      - name: Extracting Godot version
        id: extract_version
        run: |
          echo "Extracting the Godot project version..."
          godot_version=$(grep -oP 'config/features=PackedStringArray\("\K[0-9]+\.[0-9]+' ${PROJECT_PATH}/project.godot | head -n 1)
          echo "Found Godot version: $godot_version"
          echo "godot_version=$godot_version" >> $GITHUB_OUTPUT
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    needs: version
    container:
      image: barichello/godot-ci:${{ needs.version.outputs.godot_version }}
    env:
      GODOT_VERSION: ${{ needs.version.outputs.godot_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.version.outputs.build_name }}
          path: build/web
      - name: Install Butler (Official Itch.io CLI) 🎩
        run: |
          wget -O butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Push to Itch.io via Butler 🚀
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
        run: |
          butler push build/web OrbitOwlGames/develop:html5
